# `numpy`

In [4]:
import numpy as np

## Как создать массив в `numpy`?

In [2]:
a = np.array(["1", 2, "汉"])
b = np.array([1, 2, 3], dtype=np.uint16)
c = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float128)

In [3]:
a

array(['1', '2', '汉'], dtype='<U1')

In [4]:
b

array([1, 2, 3], dtype=uint16)

In [5]:
c

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float128)

In [6]:
print(c.shape)

(2, 3)


In [7]:
print(c.dtype)

float128


### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [8]:
np.zeros((2, 2)) # array of all zeroes

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [10]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [11]:
np.eye(3) # diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[-2, -1,  1, -5, -1],
       [-1,  7, -9,  9, -1]])

## Индексирование и слайсы

In [13]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[84 35 79 57  2 99 69 95 57 44]
 [12 77 38 93 73 98 50 71 25 63]
 [36 65 91 50 88 92 16 56 18 21]
 [86 73 28 66 70 41 19 65 41 19]
 [68 79 34 22 83 90 17 53 20 64]]


In [14]:
a[0]

array([84, 35, 79, 57,  2, 99, 69, 95, 57, 44])

In [15]:
a[0, 1] # the same as a[0][1]

35

In [16]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([35, 77, 65, 73, 79])

In [17]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([57, 25, 18, 41])

In [18]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([68, 34, 83, 17, 20])

In [19]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([79, 22, 90, 53, 64])

In [20]:
# все четные элементы массива:
a[a % 2 == 0]

array([84,  2, 44, 12, 38, 98, 50, 36, 50, 88, 92, 16, 56, 18, 86, 28, 66,
       70, 68, 34, 22, 90, 20, 64])

In [21]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[84, 35, 79, 57,  2, 99, 69, 95, 57, 44],
       [68, 79, 34, 22, 83, 90, 17, 53, 20, 64]])

### Для присваивания тоже работает!

In [22]:
a

array([[84, 35, 79, 57,  2, 99, 69, 95, 57, 44],
       [12, 77, 38, 93, 73, 98, 50, 71, 25, 63],
       [36, 65, 91, 50, 88, 92, 16, 56, 18, 21],
       [86, 73, 28, 66, 70, 41, 19, 65, 41, 19],
       [68, 79, 34, 22, 83, 90, 17, 53, 20, 64]])

In [23]:
a[1:-1, :] = 1
a

array([[84, 35, 79, 57,  2, 99, 69, 95, 57, 44],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [68, 79, 34, 22, 83, 90, 17, 53, 20, 64]])

In [24]:
a[:, 1:3] = np.arange(2)
a

array([[84,  0,  1, 57,  2, 99, 69, 95, 57, 44],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [68,  0,  1, 22, 83, 90, 17, 53, 20, 64]])

## Операции с `np.array`

In [41]:
a = np.random.randint(low=0, high=100, size=(3, 4))
b = np.random.randint(low=0, high=100, size=(3, 4))
c = np.random.randint(low=0, high=100, size=4)
d = 42

print(f"a: {a}", end="\n\n")
print(f"b: {b}", end="\n\n")
print(f"c: {c}", end="\n\n")

a: [[42 34 49 69]
 [88 42 58 85]
 [32 24  9 28]]

b: [[ 4 67 88 30]
 [81 74 55 87]
 [13 30 72  3]]

c: [14 25 28 54]



In [26]:
print(a.reshape((2, 6))) # the same as a.shape = (1, 6)

[[31 16 88 87 73 90]
 [88 13 84 33 22 58]]


In [31]:
print(a.T)

[[31 73 84]
 [16 90 33]
 [88 88 22]
 [87 13 58]]


In [28]:
a + b

array([[114,  85, 122, 144],
       [161, 161, 148,  81],
       [161,  77,  48, 137]])

In [29]:
a - b

array([[-52, -53,  54,  30],
       [-15,  19,  28, -55],
       [  7, -11,  -4, -21]])

In [30]:
# какое это умножение?
a * b

array([[2573, 1104, 2992, 4959],
       [6424, 6390, 5280,  884],
       [6468, 1452,  572, 4582]])

In [32]:
# а это?
a @ b.T

array([[11628, 15060, 12252],
       [16002, 18978, 12896],
       [13303, 14999, 13074]])

In [33]:
a / b

array([[0.37349398, 0.23188406, 2.58823529, 1.52631579],
       [0.82954545, 1.26760563, 1.46666667, 0.19117647],
       [1.09090909, 0.75      , 0.84615385, 0.73417722]])

In [34]:
a = np.array([[5, 4], [7, 8]])
for_pow = np.array([2, 3])

a ** for_pow

array([[ 25,  64],
       [ 49, 512]])

In [35]:
np.sqrt(b)

array([[9.11043358, 8.30662386, 5.83095189, 7.54983444],
       [9.38083152, 8.42614977, 7.74596669, 8.24621125],
       [8.77496439, 6.63324958, 5.09901951, 8.88819442]])

In [36]:
np.sum(b)

756

In [37]:
np.sum(b, axis=0)

array([248, 184, 120, 204])

In [38]:
np.min(a[0])

4

In [42]:
np.vstack([a, b])

array([[42, 34, 49, 69],
       [88, 42, 58, 85],
       [32, 24,  9, 28],
       [ 4, 67, 88, 30],
       [81, 74, 55, 87],
       [13, 30, 72,  3]])

In [43]:
np.hstack([a, b])

array([[42, 34, 49, 69,  4, 67, 88, 30],
       [88, 42, 58, 85, 81, 74, 55, 87],
       [32, 24,  9, 28, 13, 30, 72,  3]])

### Волшебный `np.vectorize`

In [44]:
pow_2 = lambda x: x ** 2

In [45]:
pow_2(np.array([2, 3, 4]))

array([ 4,  9, 16])

In [46]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [47]:
pow_2_vec = np.vectorize(pow_2)
pow_2_vec([2, 3, 4])

array([ 4,  9, 16])

### Немного про broadcasting

In [48]:
a + d

array([[ 84,  76,  91, 111],
       [130,  84, 100, 127],
       [ 74,  66,  51,  70]])

In [49]:
a + c

array([[ 56,  59,  77, 123],
       [102,  67,  86, 139],
       [ 46,  49,  37,  82]])

In [50]:
b - d

array([[-38,  25,  46, -12],
       [ 39,  32,  13,  45],
       [-29, -12,  30, -39]])

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [61]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())
print(np.max(z[-1, 1::2]))

2264565


### Задание: написать решалку линейных уравнений

In [65]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...

def solution_finder(A, y):
    if np.linalg.det(A) == 0:
        raise ValueError(f"Write {A} has no det")
    return np.linalg.inv(A) @ y

### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [66]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det

def cramer_solver(A, b):
    detA = np.linalg.det(A)
    if detA == 0:
        raise ValueError(f"Write {A} has no det")
        
    x = np.zero(A.shape[1])

    for i in range(A.shape[1]):
        tmp = copy.deepcopy(A)
        tmp[:, i] = b
        x[i] = np.linalg.det(tmp) / detA
    return x

## Few more things:

### `np.random.seed()`

In [54]:
for i in range(5):
    arr = np.arange(5)  # [0, 1, 2, 3, 4]
    np.random.seed(1)  # Reset random state
    np.random.shuffle(arr)  # Shuffle!
    print(arr)

[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]


In [56]:
np.random.seed(3)
print(np.random.random())

np.random.seed(3)
print(np.random.random())

0.5507979025745755
0.5507979025745755


### `np.isclose()`

In [59]:
np.float128(1 / 3) * 3 == 1

False

In [60]:
np.isclose(np.float128(1 / 3) * 3, 1)

True

---

# scipy.sparse

In [5]:
from scipy.sparse import csr_matrix
from sys import getsizeof

In [11]:
a = np.random.randint(0, 2, (1, 1_000_000))
print(getsizeof(a))

a_csr = csr_matrix(a)
print(getsizeof(a_csr))

8000112
56


In [7]:
a.mean()

0.499691

#### Или можно вот так вот создать:

In [8]:
values = list(range(1, 11))
row_idxs = [0, 1, 2, 0, 1, 2, 0, 1, 2, 3]
column_idxs = [4, 3, 2, 1, 1, 2, 3, 4, 0, 0]

csr_improvisation = csr_matrix((values, (row_idxs, column_idxs)))
csr_improvisation.toarray()

array([[ 0,  4,  0,  7,  1],
       [ 0,  5,  0,  2,  8],
       [ 9,  0,  9,  0,  0],
       [10,  0,  0,  0,  0]], dtype=int64)